import localFont from "next/font/local";
import "./globals.css";
import { Poppins } from "next/font/google";
import DesktopHeader from "@/components/HomePage/Header/DesktopHeader/DesktopHeader";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const poppins = Poppins({ subsets: ["latin"], weight: ['400', '500', '600', '700'], variable: "--font-poppins" })

export const metadata = {
  title: "E-Commerce Application",
  description: "Generated by SP",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins} antialiased`}
      >
        <DesktopHeader />
        {children}
      </body>
    </html>
  );
}
